version: 2
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  fixme:
    enabled: true
    issue_override:
      severity: info
    config:
      strings:
        - FIXME
        - TODO
  flog:
    enabled: true
    config:
      score_threshold: 20.0
  markdownlint:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
    config:
      file: .rubocop.yml
    channel: rubocop-1-10-0
  rubymotion:
    enabled: true
exclude_patterns:
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "Tests/"
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
  - "public/packs"
  - "public/packs-test"
  - "coverage/*"
  - "tmp/"
  - "app/components/IUX"
