default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['LETS_DO_IT_DATABASE_USER'] || 'lets_do_it' %>
  password: <%= ENV['LETS_DO_IT_DATABASE_PASS'] || 'development' %>
  host:  <%= ENV['LETS_DO_IT_DATABASE_HOST']  || '127.0.0.1' %>
  port: 5432

development:
  <<: *default
  database: lets_do_it_development
  password: development

test:
  <<: *default
  database: lets_do_it_test

production:
  <<: *default
  database: lets_do_it
