name: Rspec Actions

on: [push]

jobs:
  rspec:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.0.0

    services:
      postgres:
        image: postgres:13.2
        env:
          POSTGRES_USER: lets_do_it
          POSTGRES_PASSWORD: development
          POSTGRES_DB: lets_do_it_test
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Gem cache
      id: cache-bundle
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundle-${{ hashFiles('**/Gemfile.lock') }}

    - name: Bundle install
      env:
        RAILS_ENV: test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3 --path vendor/bundle
    - name: Install yarn
      run: npm install -g yarn

    # NOTE: Yarn cache doesn't seem to be working quite yet
    - name: Get yarn cache dir
      id: yarn-cache-dir
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Yarn cache
      id: cache-yarn
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache-dir.outputs.dir }}
        key: yarn-${{ hashFiles('**/yarn.lock') }}

    - name: Yarn install
      run: yarn install

    - name: Download Codeclimate reporter
      run: |
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      chmod +x ./cc-test-reporter

    - name: Setup DB, Run tests
      env:
        PGHOST: postgres
        PGUSER: postgres
        PGPORT: ${{ job.services.postgres.ports[5432] }}
        RAILS_ENV: test
        LETS_DO_IT_DATABASE_HOST: postgres
      run: |
        bin/rails db:create db:schema:load
        ./cc-test-reporter before-build
        bundle exec rspec

    - name: Sending Coverage Report
      run: ./cc-test-reporter after-build -t simplecov
