name: Linters

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master

jobs:
  rubocop:
    name: Rubocop Check Action
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 3.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Install Rubocop
        run: gem install rubocop
      - name: Run Rubocop
        run: rubocop
